# Generated by Django 5.2.3 on 2025-10-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventario_cantidad_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
