# Generated by Django 5.2.3 on 2025-10-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventario_cantidad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
