# Generated by Django 5.1.4 on 2025-11-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
        ('inventario', '0004_producto_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['sede', 'producto__nombre'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'sede')},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_maxima',
            field=models.PositiveIntegerField(default=1000, help_text='Capacidad máxima de almacenamiento'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_minima',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad mínima antes de reabastecimiento'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, help_text='Ubicación física en el almacén (ej: Anaquel A3)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el producto está disponible para venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del producto', null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en esta sede'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(help_text='Producto inventariado', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='sede',
            field=models.ForeignKey(help_text='Sede donde se encuentra el inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='instalaciones.sede'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['sede', 'producto'], name='inventario_sede_id_f723a9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['cantidad_actual'], name='inventario_cantida_7c1d13_idx'),
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='minimo',
        ),
    ]
