# Generated by Django 5.2.3 on 2025-10-21 16:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_certificados_empleado_comprobante_domicilio_and_more'),
        ('instalaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('categoria_activo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
                'db_table': 'categoria_activo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorServicio',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('servicios_ofrecidos', models.TextField(blank=True, help_text='Descripción de los servicios que ofrece el proveedor', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor de Servicio',
                'verbose_name_plural': 'Proveedores de Servicios',
                'db_table': 'proveedor_servicio',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('activo_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único del activo (ej: MAQ-001, MOB-015)', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='Precio de compra del activo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Descripción específica de la ubicación dentro del espacio', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del activo', null=True, upload_to='activos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL)),
                ('espacio', models.ForeignKey(blank=True, help_text='Espacio específico donde se encuentra el activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='instalaciones.espacio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='instalaciones.sede')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='gestion_equipos.categoriaactivo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'activo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('mantenimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(help_text='Descripción del trabajo a realizar')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales o hallazgos durante el mantenimiento', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion_equipos.activo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado_responsable', models.ForeignKey(blank=True, help_text='Empleado responsable del mantenimiento interno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to='empleados.empleado')),
                ('proveedor_servicio', models.ForeignKey(blank=True, help_text='Proveedor externo (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='gestion_equipos.proveedorservicio')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('orden_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(help_text='Número único de orden (ej: OM-2025-001)', max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('tiempo_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado en horas', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('materiales_necesarios', models.TextField(blank=True, help_text='Lista de materiales o repuestos necesarios', null=True)),
                ('estado_orden', models.CharField(choices=[('creada', 'Creada'), ('aprobada', 'Aprobada'), ('en_ejecucion', 'En Ejecución'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='creada', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='gestion_equipos.mantenimiento')),
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento',
                'verbose_name_plural': 'Órdenes de Mantenimiento',
                'db_table': 'orden_mantenimiento',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['codigo'], name='activo_codigo_47e3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['estado'], name='activo_estado_399078_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['sede'], name='activo_sede_id_9d82c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['activo', 'estado'], name='mantenimien_activo__30f522_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['fecha_programada'], name='mantenimien_fecha_p_87c814_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['tipo_mantenimiento'], name='mantenimien_tipo_ma_78a783_idx'),
        ),
    ]
