# Generated by Django 5.2.3 on 2025-10-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepasarela',
            options={'verbose_name': 'Detalle de Pasarela', 'verbose_name_plural': 'Detalles de Pasarela'},
        ),
        migrations.AlterModelTable(
            name='detallepasarela',
            table='detalle_pasarela',
        ),
    ]
