# Generated by Django 5.2.3 on 2025-10-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detallepasarela_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepasarela',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasarelapago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=50),
        ),
    ]
