# Generated by Django 5.1.4 on 2025-11-07 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('instalaciones', '0001_initial'),
        ('inventario', '0004_producto_codigo'),
        ('ventas', '0003_venta_estado_alter_detallepasarela_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Suma de todos los productos antes de descuentos', max_digits=10)),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado al total de la venta', max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, help_text='IVA calculado (16% en México)', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final a pagar', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la venta')),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la venta')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente que realiza la compra (opcional para ventas rápidas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_productos', to='clientes.cliente')),
                ('empleado', models.ForeignKey(help_text='Cajero que realizó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(help_text='Sede donde se realizó la venta', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_productos', to='instalaciones.sede')),
            ],
            options={
                'verbose_name': 'Venta de Producto',
                'verbose_name_plural': 'Ventas de Productos',
                'db_table': 'venta_producto',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaProducto',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades vendidas')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la venta', max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado a este producto específico', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='precio_unitario * cantidad', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='subtotal - descuento', max_digits=10)),
                ('producto', models.ForeignKey(help_text='Producto vendido (PROTECT para mantener historial)', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(help_text='Venta a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ventaproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta_producto',
            },
        ),
        migrations.AddIndex(
            model_name='ventaproducto',
            index=models.Index(fields=['-fecha_venta'], name='venta_produ_fecha_v_c2fedf_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaproducto',
            index=models.Index(fields=['sede', '-fecha_venta'], name='venta_produ_sede_id_52605f_idx'),
        ),
        migrations.AddIndex(
            model_name='ventaproducto',
            index=models.Index(fields=['estado'], name='venta_produ_estado_12b005_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleventaproducto',
            index=models.Index(fields=['venta', 'producto'], name='detalle_ven_venta_i_a5886a_idx'),
        ),
    ]
