# Generated by Django 5.1.4 on 2026-06-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ventaproducto_detalleventaproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepasarela',
            name='pasarela',
        ),
        migrations.RemoveField(
            model_name='detallepasarela',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.DeleteModel(
            name='PasarelaPago',
        ),
        migrations.DeleteModel(
            name='DetallePasarela',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
