# Generated by Django 5.2.3 on 2025-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_name',
            field=models.CharField(default='Cliente desconocido', max_length=100),
        ),
    ]
