# Generated by Django 5.2.3 on 2025-10-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_factura_cliente_id_factura_cliente_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente_name',
            field=models.CharField(max_length=100),
        ),
    ]
