# Generated by Django 5.2.3 on 2025-10-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturacion', '0003_alter_factura_cliente_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente_name',
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
