# Generated by Django 5.2.3 on 2025-09-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.persona')),
                ('puesto', models.CharField(max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('nss', models.CharField(blank=True, max_length=11)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instalaciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('turno', models.CharField(max_length=50)),
                ('espacio', models.ManyToManyField(to='instalaciones.espacio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('especialidad', models.CharField(max_length=100)),
                ('certificaciones', models.CharField(blank=True, max_length=255)),
                ('turno', models.CharField(max_length=50)),
                ('espacio', models.ManyToManyField(to='instalaciones.espacio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLimpieza',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('turno', models.CharField(max_length=50)),
                ('espacio', models.ManyToManyField(to='instalaciones.espacio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorEspacio',
            fields=[
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('turno', models.CharField(max_length=50)),
                ('espacio', models.ManyToManyField(to='instalaciones.espacio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.sede')),
            ],
        ),
    ]
