# Generated by Django 5.2.3 on 2025-10-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='certificados',
            field=models.FileField(blank=True, null=True, upload_to='documentos/certificados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='documentos/comprobantes/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='identificacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/identificaciones/'),
        ),
    ]
