# Generated by Django 5.1.4 on 2025-11-22 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_certificados_empleado_comprobante_domicilio_and_more'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_espacio', models.CharField(choices=[('bano', 'Baño'), ('vestidor', 'Vestidor'), ('gimnasio', 'Gimnasio'), ('alberca', 'Alberca'), ('recepcion', 'Recepción'), ('oficina', 'Oficina'), ('estacionamiento', 'Estacionamiento'), ('areas_comunes', 'Áreas Comunes'), ('otro', 'Otro')], max_length=50)),
                ('duracion_estimada', models.IntegerField(help_text='Duración estimada en minutos')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarea de Limpieza',
                'verbose_name_plural': 'Tareas de Limpieza',
                'ordering': ['-prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('observaciones_completado', models.TextField(blank=True, help_text='Observaciones al completar la tarea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_limpieza_creadas', to='empleados.empleado')),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to='empleados.personallimpieza')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.espacio')),
                ('personal_limpieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='empleados.personallimpieza')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.tarealimpieza')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('calificacion', models.IntegerField(blank=True, help_text='Calificación de 1 a 5 estrellas', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='empleados.asignaciontarea')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_limpieza', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Checklist de Limpieza',
                'verbose_name_plural': 'Checklists de Limpieza',
            },
        ),
        migrations.CreateModel(
            name='HorarioLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.espacio')),
                ('personal_limpieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='empleados.personallimpieza')),
            ],
            options={
                'verbose_name': 'Horario de Limpieza',
                'verbose_name_plural': 'Horarios de Limpieza',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
