# Generated by Django 5.2.8 on 2025-11-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_tarealimpieza_asignaciontarea_checklistlimpieza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontarea',
            name='fecha',
            field=models.DateField(help_text='Fecha cuando se asignó la tarea'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora exacta de completado', null=True),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp exacto de cuando se creó la asignación'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora cuando empleado completó la tarea (automático)', null=True),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Hora cuando se asignó la tarea (automático)', null=True),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas del administrador al asignar la tarea'),
        ),
        migrations.AlterField(
            model_name='asignaciontarea',
            name='observaciones_completado',
            field=models.TextField(blank=True, help_text='Observaciones del empleado al completar (desde app móvil)'),
        ),
    ]
