# Generated by Django 5.2.3 on 2025-09-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_credencial', models.CharField(max_length=20)),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.persona')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('autorizado', models.BooleanField()),
                ('motivo_denegado', models.CharField(blank=True, max_length=255)),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acceso.credencial')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instalaciones.espacio')),
            ],
        ),
    ]
