# Generated by Django 5.1.4 on 2025-11-13 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
        ('clientes', '0002_cliente_sede'),
        ('control_acceso', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credencial',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Credencial', 'verbose_name_plural': 'Credenciales'},
        ),
        migrations.AlterModelOptions(
            name='registroacceso',
            options={'ordering': ['-fecha_hora_entrada'], 'verbose_name': 'Registro de Acceso', 'verbose_name_plural': 'Registros de Accesos'},
        ),
        migrations.RemoveField(
            model_name='registroacceso',
            name='credencial',
        ),
        migrations.RemoveField(
            model_name='registroacceso',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='registroacceso',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='credencial',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='credencial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='fecha_hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='membresia_estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='membresia_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_registrados', to='authentication.persona'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='instalaciones.sede'),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('revocada', 'Revocada'), ('expirada', 'Expirada'), ('suspendida', 'Suspendida')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='authentication.persona'),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='motivo_denegado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['cliente', 'fecha_hora_entrada'], name='control_acc_cliente_cbe1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['sede', 'fecha_hora_entrada'], name='control_acc_sede_id_0551a1_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['autorizado', 'fecha_hora_entrada'], name='control_acc_autoriz_2507da_idx'),
        ),
    ]
