# Generated by Django 5.1.4 on 2025-11-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sede',
            field=models.ForeignKey(default=1, help_text='Sede principal del cliente', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='instalaciones.sede'),
            preserve_default=False,
        ),
    ]
