# Generated by Django 5.2.3 on 2025-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('pase_dia', 'Pase del Día'), ('pase_semana', 'Pase Semanal')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, help_text='Duración de la membresía en días', null=True)),
                ('beneficios', models.TextField(blank=True, help_text='Lista de beneficios incluidos', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la membresía está disponible para venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['tipo', 'precio'],
            },
        ),
    ]
