# Generated by Django 5.1.4 on 2025-10-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la suscripción', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='clientes.cliente')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Suscripción de Membresía',
                'verbose_name_plural': 'Suscripciones de Membresías',
                'db_table': 'suscripcion_membresia',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
