# Generated by Django 5.1.4 on 2025-10-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
        ('membresias', '0002_suscripcionmembresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='espacios_incluidos',
            field=models.ManyToManyField(blank=True, help_text='Espacios a los que da acceso esta membresía', related_name='membresias', to='instalaciones.espacio'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='permite_todas_sedes',
            field=models.BooleanField(default=False, help_text='Si es True, da acceso a todas las sedes (plan premium/corporativo)'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede a la que pertenece esta membresía. Si es null, es multi-sede', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='instalaciones.sede'),
        ),
        migrations.AddField(
            model_name='suscripcionmembresia',
            name='sede_suscripcion',
            field=models.ForeignKey(blank=True, help_text='Sede donde se realizó la suscripción (se hereda de la membresía)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='instalaciones.sede'),
        ),
    ]
