# Generated by Django 5.2.3 on 2025-10-25 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_certificados_empleado_comprobante_domicilio_and_more'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_default', models.DurationField(help_text='Duración por defecto en formato HH:MM:SS')),
                ('color_hex', models.CharField(default='#3b82f6', help_text='Color para mostrar en calendario (#RRGGBB)', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bloqueo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('evento_especial', 'Evento Especial'), ('vacaciones', 'Vacaciones del Entrenador'), ('reparacion', 'Reparación del Espacio'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('entrenador', models.ForeignKey(blank=True, help_text='Entrenador bloqueado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='empleados.entrenador')),
                ('espacio', models.ForeignKey(blank=True, help_text='Espacio bloqueado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='instalaciones.espacio')),
            ],
            options={
                'verbose_name': 'Bloqueo de Horario',
                'verbose_name_plural': 'Bloqueos de Horarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual este horario está vigente')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha hasta la cual este horario está vigente (opcional)', null=True)),
                ('cupo_maximo', models.PositiveIntegerField(default=20, help_text='Número máximo de personas que pueden asistir')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('entrenador', models.ForeignKey(help_text='Entrenador asignado a este horario', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='empleados.entrenador')),
                ('espacio', models.ForeignKey(help_text='Espacio donde se realizará la actividad', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='instalaciones.espacio')),
                ('tipo_actividad', models.ForeignKey(help_text='Tipo de actividad a realizar', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='horarios.tipoactividad')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('espacio', 'dia_semana', 'hora_inicio', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha específica de la sesión')),
                ('hora_inicio_override', models.TimeField(blank=True, help_text='Hora de inicio alternativa para esta sesión', null=True)),
                ('hora_fin_override', models.TimeField(blank=True, help_text='Hora de fin alternativa para esta sesión', null=True)),
                ('cupo_override', models.PositiveIntegerField(blank=True, help_text='Cupo alternativo para esta sesión', null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida')], default='programada', max_length=20)),
                ('asistentes_registrados', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('entrenador_override', models.ForeignKey(blank=True, help_text='Entrenador sustituto para esta sesión específica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_sustitutas', to='empleados.entrenador')),
                ('espacio_override', models.ForeignKey(blank=True, help_text='Espacio alternativo para esta sesión específica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_override', to='instalaciones.espacio')),
                ('horario', models.ForeignKey(help_text='Horario base del cual se genera esta sesión', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='horarios.horario')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clases',
                'ordering': ['fecha', 'horario__hora_inicio'],
                'unique_together': {('horario', 'fecha')},
            },
        ),
    ]
