# Generated by Django 5.2.3 on 2025-10-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0002_empleado_certificados_empleado_comprobante_domicilio_and_more'),
        ('gestion_equipos', '0001_initial'),
        ('horarios', '0001_initial'),
        ('instalaciones', '0001_initial'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='clientes.cliente')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_suscritos', to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Membresía de Cliente',
                'verbose_name_plural': 'Membresías de Clientes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_sesion', models.CharField(choices=[('individual', 'Sesión Individual'), ('pareja', 'Sesión en Pareja'), ('grupal_pequeno', 'Grupo Pequeño (3-5 personas)')], default='individual', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente Aprobación'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='pendiente', max_length=20)),
                ('objetivo', models.TextField(help_text='Objetivo específico de la sesión')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la sesión personalizada', max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('notas_entrenador', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_entrenador', to='clientes.cliente')),
                ('clientes_adicionales', models.ManyToManyField(blank=True, help_text='Clientes adicionales para sesiones en pareja o grupales', related_name='sesiones_grupales', to='clientes.cliente')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_personalizadas', to='empleados.entrenador')),
                ('espacio', models.ForeignKey(blank=True, help_text='Espacio donde se realizará la sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instalaciones.espacio')),
            ],
            options={
                'verbose_name': 'Reserva de Entrenador',
                'verbose_name_plural': 'Reservas de Entrenadores',
                'ordering': ['fecha_sesion', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_uso', 'En Uso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tiempo_uso_real', models.DurationField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_equipos.activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_equipos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Reserva de Equipo',
                'verbose_name_plural': 'Reservas de Equipos',
                'ordering': ['fecha_reserva', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EquipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.PositiveIntegerField(default=1, help_text='Cantidad de este equipo necesaria para la actividad')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio tener este equipo para realizar la actividad')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_relacionadas', to='gestion_equipos.activo')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_necesarios', to='horarios.tipoactividad')),
            ],
            options={
                'verbose_name': 'Equipo por Actividad',
                'verbose_name_plural': 'Equipos por Actividad',
                'unique_together': {('tipo_actividad', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='ReservaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('asistio', 'Asistió'), ('no_asistio', 'No Asistió'), ('no_show', 'No Show')], default='confirmada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='clientes.cliente')),
                ('sesion_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='horarios.sesionclase')),
            ],
            options={
                'verbose_name': 'Reserva de Clase',
                'verbose_name_plural': 'Reservas de Clases',
                'ordering': ['-fecha_reserva'],
                'unique_together': {('cliente', 'sesion_clase')},
            },
        ),
    ]
