# Generated by Django 5.2.8 on 2025-11-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_clientemembresia_reservaentrenador_reservaequipo_and_more'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede donde está disponible esta actividad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_actividad', to='instalaciones.sede'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tipoactividad',
            unique_together={('nombre', 'sede')},
        ),
    ]
